export const THEMES = {
  videojuegos: {
    id: "videojuegos",
    name: "Videojuegos",
    emoji: "🎮",
    dark: true,
    font: "'Press Start 2P', monospace",
    fontScale: 0.62,
    colors: { bg: "#111827", surface: "#1F2937", primary: "#22C55E", text: "#FFFFFF", accent: "#EF4444", soft: "#FBBF24" },
    image: "https://images.unsplash.com/photo-1660507224958-729c18ba1277?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🍄", "⭐", "👾", "🕹️", "🏆", "💎"],
    copy: {
      badge: (n) => `${n}MUNDO`,
      title: (n, a) => `¡${n} sube al nivel ${a}!`,
      subtitle: (a) => `CUMPLE ${a} AÑITOS 🎂`,
      countdown: "⏳ La aventura comienza en",
      details: "▼ Datos de la misión ▼",
      arrive: "🧭 Cómo llegar",
      rsvpTitle: "🎮 Registro de jugadores",
      rsvpSubtitle: "Confirma tu asistencia para reservar tu lugar en la aventura",
      confirm: "🪙 CONFIRMAR ASISTENCIA",
      successTitle: "★ ¡JUGADOR REGISTRADO! ★",
      successExtra: "+1UP 🍄",
      punctual: "¡Llega puntual, la aventura no espera!",
      msgLabel: (n) => `Mensaje para ${n} (opcional)`,
    },
  },
  princesas: {
    id: "princesas",
    name: "Princesas",
    emoji: "👑",
    dark: false,
    font: "'Dancing Script', cursive",
    fontScale: 1.25,
    colors: { bg: "#FDF2F8", surface: "#FFFFFF", primary: "#EC4899", text: "#831843", accent: "#F59E0B", soft: "#FBCFE8" },
    image: "https://images.unsplash.com/photo-1650571057388-3921855f66c9?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["👑", "🏰", "✨", "🌸", "🦋", "💖"],
    copy: {
      badge: (n) => `Reino de ${n}`,
      title: (n, a) => `¡La princesa ${n} cumple ${a}!`,
      subtitle: (a) => `CUMPLE ${a} AÑITOS 🎂`,
      countdown: "⏳ El baile real comienza en",
      details: "✨ Detalles de la celebración real ✨",
      arrive: "🏰 Cómo llegar al castillo",
      rsvpTitle: "👑 Lista de invitados reales",
      rsvpSubtitle: "Confirma tu asistencia para reservar tu lugar en el gran baile",
      confirm: "💖 CONFIRMAR ASISTENCIA",
      successTitle: "✨ ¡INVITACIÓN REAL ACEPTADA! ✨",
      successExtra: "👑💖",
      punctual: "¡Llega puntual, la carroza no espera!",
      msgLabel: (n) => `Mensaje para ${n} (opcional)`,
    },
  },
  superheroes: {
    id: "superheroes",
    name: "Superhéroes",
    emoji: "🦸",
    dark: false,
    font: "'Bangers', cursive",
    fontScale: 1.1,
    colors: { bg: "#EFF6FF", surface: "#FFFFFF", primary: "#EF4444", text: "#1E3A8A", accent: "#EAB308", soft: "#BFDBFE" },
    image: "https://images.unsplash.com/photo-1760954185931-40d5b65fbb86?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["💥", "⚡", "🦸", "🛡️", "💫", "🌟"],
    copy: {
      badge: (n) => `Escuadrón ${n}`,
      title: (n, a) => `¡${n} cumple ${a} y salva el día!`,
      subtitle: (a) => `CUMPLE ${a} AÑITOS 🎂`,
      countdown: "⏳ La misión heroica comienza en",
      details: "💥 Datos de la operación 💥",
      arrive: "🗺️ Cómo llegar al cuartel",
      rsvpTitle: "🦸 Reclutamiento de héroes",
      rsvpSubtitle: "Confirma tu asistencia y únete al escuadrón",
      confirm: "⚡ CONFIRMAR ASISTENCIA",
      successTitle: "💥 ¡HÉROE RECLUTADO! 💥",
      successExtra: "⚡🦸",
      punctual: "¡Llega puntual, la ciudad te necesita!",
      msgLabel: (n) => `Mensaje para ${n} (opcional)`,
    },
  },
  dinosaurios: {
    id: "dinosaurios",
    name: "Dinosaurios",
    emoji: "🦖",
    dark: false,
    font: "'Bowlby One SC', cursive",
    fontScale: 0.85,
    colors: { bg: "#F0FDF4", surface: "#FFFFFF", primary: "#16A34A", text: "#14532D", accent: "#D97706", soft: "#BBF7D0" },
    image: "https://images.unsplash.com/photo-1743600160621-144e62297185?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🦖", "🦕", "🌋", "🌿", "🥚", "🐾"],
    copy: {
      badge: (n) => `Dinolandia de ${n}`,
      title: (n, a) => `¡${n} cumple ${a} dino-años!`,
      subtitle: (a) => `CUMPLE ${a} AÑITOS 🎂`,
      countdown: "⏳ La expedición comienza en",
      details: "🦴 Datos de la expedición 🦴",
      arrive: "🗺️ Cómo llegar al valle jurásico",
      rsvpTitle: "🦖 Registro de exploradores",
      rsvpSubtitle: "Confirma tu asistencia para unirte a la expedición",
      confirm: "🦕 CONFIRMAR ASISTENCIA",
      successTitle: "🦖 ¡EXPLORADOR REGISTRADO! 🦖",
      successExtra: "🐾🌋",
      punctual: "¡Llega puntual, los dinos no esperan!",
      msgLabel: (n) => `Mensaje para ${n} (opcional)`,
    },
  },
  espacio: {
    id: "espacio",
    name: "Espacio",
    emoji: "🚀",
    dark: true,
    font: "'Space Grotesk', sans-serif",
    fontScale: 1,
    colors: { bg: "#0F172A", surface: "#1E293B", primary: "#8B5CF6", text: "#FFFFFF", accent: "#38BDF8", soft: "#FBBF24" },
    image: "https://images.unsplash.com/photo-1656464868371-602be27fd4c2?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🚀", "🪐", "⭐", "👨‍🚀", "🛸", "🌙"],
    copy: {
      badge: (n) => `Misión ${n}`,
      title: (n, a) => `¡${n} despega al año ${a}!`,
      subtitle: (a) => `CUMPLE ${a} AÑITOS 🎂`,
      countdown: "⏳ El despegue es en",
      details: "🛰️ Datos de la misión espacial 🛰️",
      arrive: "🧭 Coordenadas de la base",
      rsvpTitle: "🚀 Registro de astronautas",
      rsvpSubtitle: "Confirma tu asistencia para abordar la nave",
      confirm: "🛸 CONFIRMAR ASISTENCIA",
      successTitle: "⭐ ¡ASTRONAUTA A BORDO! ⭐",
      successExtra: "🚀🪐",
      punctual: "¡Llega puntual, el cohete no espera!",
      msgLabel: (n) => `Mensaje para ${n} (opcional)`,
    },
  },
  unicornios: {
    id: "unicornios",
    name: "Unicornios",
    emoji: "🦄",
    dark: false,
    font: "'Caveat Brush', cursive",
    fontScale: 1.2,
    colors: { bg: "#FAF5FF", surface: "#FFFFFF", primary: "#D946EF", text: "#4A044E", accent: "#06B6D4", soft: "#F5D0FE" },
    image: "https://images.unsplash.com/photo-1604937455095-ef2fe3d46fcd?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🦄", "🌈", "☁️", "⭐", "🍭", "💜"],
    copy: {
      badge: (n) => `Mundo mágico de ${n}`,
      title: (n, a) => `¡${n} cumple ${a} añitos mágicos!`,
      subtitle: (a) => `CUMPLE ${a} AÑITOS 🎂`,
      countdown: "⏳ La magia comienza en",
      details: "🌈 Detalles de la fiesta mágica 🌈",
      arrive: "🗺️ Cómo llegar al arcoíris",
      rsvpTitle: "🦄 Registro de invitados mágicos",
      rsvpSubtitle: "Confirma tu asistencia para entrar al mundo mágico",
      confirm: "🌈 CONFIRMAR ASISTENCIA",
      successTitle: "🦄 ¡INVITADO MÁGICO REGISTRADO! 🦄",
      successExtra: "🌈✨",
      punctual: "¡Llega puntual, la magia no espera!",
      msgLabel: (n) => `Mensaje para ${n} (opcional)`,
    },
  },
  magia: {
    id: "magia",
    name: "Sorpresa Mágica",
    emoji: "🎩",
    dark: true,
    font: "'Cinzel Decorative', cursive",
    fontScale: 0.7,
    colors: { bg: "#170B2E", surface: "#2A1750", primary: "#A855F7", text: "#F5F3FF", accent: "#FBBF24", soft: "#C4B5FD" },
    image: "https://images.unsplash.com/photo-1703379943611-64676d5e4c96?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🎩", "🪄", "✨", "⭐", "🔮", "🎆"],
    copy: {
      badge: (n) => `Función mágica de ${n}`,
      title: (n, a) => `¡${n} cumple ${a} años de magia!`,
      subtitle: (a) => `CUMPLE ${a} AÑITOS 🎂`,
      countdown: "🪄 El gran truco comienza en",
      details: "🔮 Detalles del espectáculo 🔮",
      arrive: "🎩 Cómo llegar al teatro mágico",
      rsvpTitle: "🪄 Registro de magos y magas",
      rsvpSubtitle: "Confirma tu asistencia para el gran truco final",
      confirm: "✨ CONFIRMAR ASISTENCIA",
      successTitle: "🎩 ¡ABRACADABRA! YA ESTÁS DENTRO 🎩",
      successExtra: "🪄✨",
      punctual: "¡Llega puntual, la magia no se repite!",
      msgLabel: (n) => `Mensaje para ${n} (opcional)`,
    },
  },
  circo: {
    id: "circo",
    name: "Circo",
    emoji: "🎪",
    dark: false,
    font: "'Bungee', cursive",
    fontScale: 0.75,
    colors: { bg: "#FFF9E6", surface: "#FFFFFF", primary: "#DC2626", text: "#7C2D12", accent: "#EAB308", soft: "#FEF3C7" },
    image: "https://images.unsplash.com/photo-1558180227-93c31d143df3?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🎪", "🎡", "🍿", "🎈", "🤹", "🦁"],
    copy: {
      badge: (n) => `Gran Carpa de ${n}`,
      title: (n, a) => `¡${n} cumple ${a} bajo la carpa!`,
      subtitle: (a) => `CUMPLE ${a} AÑITOS 🎂`,
      countdown: "🎪 La función empieza en",
      details: "🎟️ Detalles de la función 🎟️",
      arrive: "🗺️ Cómo llegar a la carpa",
      rsvpTitle: "🤹 Registro de artistas",
      rsvpSubtitle: "Confirma tu asistencia para el mejor show del año",
      confirm: "🎟️ CONFIRMAR ASISTENCIA",
      successTitle: "🎪 ¡ENTRADA CONFIRMADA! 🎪",
      successExtra: "🎡🍿",
      punctual: "¡Llega puntual, la función no espera!",
      msgLabel: (n) => `Mensaje para ${n} (opcional)`,
    },
  },
  piratas: {
    id: "piratas",
    name: "Piratas",
    emoji: "🏴‍☠️",
    dark: true,
    font: "'Pirata One', cursive",
    fontScale: 1.3,
    colors: { bg: "#0C2340", surface: "#163A5F", primary: "#D97706", text: "#FEF3C7", accent: "#F87171", soft: "#93C5FD" },
    image: "https://images.unsplash.com/photo-1668816102414-8b3a0f33107d?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🏴‍☠️", "⚓", "🗺️", "💰", "🦜", "⛵"],
    copy: {
      badge: (n) => `Tripulación de ${n}`,
      title: (n, a) => `¡Capitán ${n} cumple ${a} años!`,
      subtitle: (a) => `CUMPLE ${a} AÑITOS 🎂`,
      countdown: "⚓ Zarpamos en",
      details: "🗺️ Datos del tesoro 🗺️",
      arrive: "🧭 Cómo llegar al puerto",
      rsvpTitle: "🏴‍☠️ Alistamiento de la tripulación",
      rsvpSubtitle: "Confirma tu asistencia para zarpar rumbo a la aventura",
      confirm: "💰 CONFIRMAR ASISTENCIA",
      successTitle: "⚓ ¡A BORDO, GRUMETE! ⚓",
      successExtra: "🏴‍☠️💰",
      punctual: "¡Llega puntual, el barco zarpa sin avisar!",
      msgLabel: (n) => `Mensaje para ${n} (opcional)`,
    },
  },
  sirenas: {
    id: "sirenas",
    name: "Sirenas",
    emoji: "🧜‍♀️",
    dark: false,
    font: "'Comfortaa', cursive",
    fontScale: 0.95,
    colors: { bg: "#ECFEFF", surface: "#FFFFFF", primary: "#0891B2", text: "#164E63", accent: "#F472B6", soft: "#A5F3FC" },
    image: "https://images.unsplash.com/photo-1533431557381-51a6546cf7ce?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🧜‍♀️", "🐚", "🫧", "🐠", "🌊", "⭐"],
    copy: {
      badge: (n) => `Reino submarino de ${n}`,
      title: (n, a) => `¡La sirena ${n} cumple ${a} años!`,
      subtitle: (a) => `CUMPLE ${a} AÑITOS 🎂`,
      countdown: "🫧 La aventura submarina empieza en",
      details: "🐚 Detalles del arrecife 🐚",
      arrive: "🌊 Cómo llegar al océano",
      rsvpTitle: "🧜‍♀️ Registro de sirenas y tritones",
      rsvpSubtitle: "Confirma tu asistencia para nadar en la fiesta",
      confirm: "🐚 CONFIRMAR ASISTENCIA",
      successTitle: "🌊 ¡YA ERES PARTE DEL ARRECIFE! 🌊",
      successExtra: "🧜‍♀️🐠",
      punctual: "¡Llega puntual, la marea no espera!",
      msgLabel: (n) => `Mensaje para ${n} (opcional)`,
    },
  },
  safari: {
    id: "safari",
    name: "Safari",
    emoji: "🦁",
    dark: false,
    font: "'Baloo 2', cursive",
    fontScale: 0.95,
    colors: { bg: "#FFF7ED", surface: "#FFFFFF", primary: "#B45309", text: "#422006", accent: "#16A34A", soft: "#FDE68A" },
    image: "https://images.unsplash.com/photo-1754424578467-7c219061e45e?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🦁", "🐘", "🦒", "🌿", "🐾", "🌅"],
    copy: {
      badge: (n) => `Safari de ${n}`,
      title: (n, a) => `¡${n} cumple ${a} años en la sabana!`,
      subtitle: (a) => `CUMPLE ${a} AÑITOS 🎂`,
      countdown: "🐾 La expedición safari sale en",
      details: "🌍 Datos de la expedición 🌍",
      arrive: "🗺️ Cómo llegar al safari",
      rsvpTitle: "🦁 Registro de exploradores",
      rsvpSubtitle: "Confirma tu asistencia para la aventura en la sabana",
      confirm: "🐘 CONFIRMAR ASISTENCIA",
      successTitle: "🦒 ¡EXPLORADOR LISTO PARA EL SAFARI! 🦒",
      successExtra: "🦁🌿",
      punctual: "¡Llega puntual, la manada no espera!",
      msgLabel: (n) => `Mensaje para ${n} (opcional)`,
    },
  },
  granja: {
    id: "granja",
    name: "Granja",
    emoji: "🐮",
    dark: false,
    font: "'Chewy', cursive",
    fontScale: 0.95,
    colors: { bg: "#FFFBEB", surface: "#FFFFFF", primary: "#CA8A04", text: "#713F12", accent: "#DC2626", soft: "#FEF08A" },
    image: "https://images.unsplash.com/photo-1768392927049-f0d92490fb5f?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🐮", "🐑", "🐔", "🐷", "🌾", "🚜"],
    copy: {
      badge: (n) => `Granja de ${n}`,
      title: (n, a) => `¡${n} cumple ${a} añitos en la granja!`,
      subtitle: (a) => `CUMPLE ${a} AÑITOS 🎂`,
      countdown: "🚜 El paseo por la granja empieza en",
      details: "🌾 Detalles del corral 🌾",
      arrive: "🗺️ Cómo llegar a la granja",
      rsvpTitle: "🐮 Registro de granjeritos",
      rsvpSubtitle: "Confirma tu asistencia para dar de comer a los animalitos",
      confirm: "🐔 CONFIRMAR ASISTENCIA",
      successTitle: "🐷 ¡YA ERES PARTE DE LA GRANJA! 🐷",
      successExtra: "🐮🌾",
      punctual: "¡Llega puntual, el gallo ya cantó!",
      msgLabel: (n) => `Mensaje para ${n} (opcional)`,
    },
  },
};

export const THEME_LIST = Object.values(THEMES);

export function formatDateEs(dateStr) {
  if (!dateStr) return "";
  const [y, m, d] = dateStr.split("-").map(Number);
  const date = new Date(y, m - 1, d);
  const s = date.toLocaleDateString("es-CO", { weekday: "long", day: "numeric", month: "long", year: "numeric" });
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export function formatTimeEs(timeStr) {
  if (!timeStr) return "";
  const [h, min] = timeStr.split(":").map(Number);
  const period = h < 12 ? "de la mañana" : h < 19 ? "de la tarde" : "de la noche";
  const h12 = h % 12 === 0 ? 12 : h % 12;
  return `${h12}:${String(min).padStart(2, "0")} ${period}`;
}

export function calendarUrl(inv) {
  if (!inv.event_date || !inv.event_time) return "#";
  const start = `${inv.event_date.replace(/-/g, "")}T${inv.event_time.replace(":", "")}00`;
  const [h, m] = inv.event_time.split(":").map(Number);
  const endH = Math.min(h + 4, 23);
  const end = `${inv.event_date.replace(/-/g, "")}T${String(endH).padStart(2, "0")}${String(m).padStart(2, "0")}00`;
  const params = new URLSearchParams({
    action: "TEMPLATE",
    text: `Cumpleaños de ${inv.child_name} 🎂`,
    dates: `${start}/${end}`,
    details: `Cumpleaños número ${inv.age} de ${inv.child_full_name || inv.child_name}`,
    location: `${inv.venue}${inv.address ? ", " + inv.address : ""}`,
  });
  return `https://www.google.com/calendar/render?${params.toString()}`;
}

export function whatsappUrl(inv) {
  if (!inv.whatsapp) return null;
  const num = inv.whatsapp.replace(/\D/g, "");
  const text = encodeURIComponent(
    `¡Hola! Confirmo mi asistencia al cumpleaños de ${inv.child_name} 🎂 el ${formatDateEs(inv.event_date)}. Somos: `
  );
  return `https://wa.me/${num}?text=${text}`;
}
