export const CATEGORIES = [
  { id: "cumple_infantil", name: "Cumpleaños infantil", emoji: "🎈" },
  { id: "cumple_adulto", name: "Cumpleaños de adultos", emoji: "🥳" },
  { id: "boda", name: "Bodas", emoji: "💍" },
  { id: "partido", name: "Ver el partido", emoji: "⚽" },
  { id: "conferencia", name: "Conferencias", emoji: "💼" },
  { id: "bautizo", name: "Bautizo", emoji: "🕊️" },
  { id: "confirmacion", name: "Confirmación", emoji: "✝️" },
  { id: "parche", name: "Parche y salidas", emoji: "🍻" },
  { id: "reto_deportivo", name: "Running y retos", emoji: "🏃" },
  { id: "novena", name: "Novena de Aguinaldos", emoji: "🎄" },
];

// Per-category field labels/placeholders and fallback display name, shared by
// Builder.jsx (creation form) and AdminVentas.jsx (manual creation form).
export const CATEGORY_FIELDS = {
  cumple_infantil: {
    nameLabel: "Nombre del peque *", namePlaceholder: "Gabriel", fallbackName: "Tu peque", showAge: true, ageLabel: "Edad que cumple *", showFullName: true, showSubtitle: true,
    subtitleLabel: "Temática o nota especial (opcional)", subtitlePlaceholder: "Ej: Temática Mario Bros · o código de vestimenta",
  },
  cumple_adulto: {
    nameLabel: "Nombre del festejado *", namePlaceholder: "Andrea", fallbackName: "El festejado", showAge: true, ageLabel: "Edad que cumple *", showFullName: true, showSubtitle: true,
    subtitleLabel: "Temática o nota especial (opcional)", subtitlePlaceholder: "Ej: Código de vestimenta: elegante casual",
    dressCodeLabel: "Código de vestimenta (opcional)", dressCodePlaceholder: "Ej: Casual elegante",
  },
  boda: {
    nameLabel: "Nombres de los novios *", namePlaceholder: "Juan & María", fallbackName: "Los novios", showAge: false, showSubtitle: true,
    subtitleLabel: "Detalle especial (opcional)", subtitlePlaceholder: "Ceremonia religiosa seguida de recepción",
    dressCodeLabel: "Etiqueta (opcional)", dressCodePlaceholder: "Ej: Etiqueta rigurosa · Paleta dorados y tierras",
  },
  partido: {
    nameLabel: "¿Quién invita? *", namePlaceholder: "Andrés", fallbackName: "El anfitrión", showAge: false, showSubtitle: true,
    subtitleLabel: "¿Qué partido? (opcional)", subtitlePlaceholder: "Colombia 🇨🇴 vs Argentina 🇦🇷",
    dressCodeLabel: "Código de vestimenta (opcional)", dressCodePlaceholder: "Ej: Camiseta de tu equipo",
  },
  conferencia: {
    nameLabel: "Nombre del evento *", namePlaceholder: "Cumbre de Liderazgo Bogotá 2026", fallbackName: "Tu evento", showAge: false, showSubtitle: true,
    subtitleLabel: "Eslogan u organizador (opcional)", subtitlePlaceholder: "Organiza: Cámara de Comercio · Networking + charlas",
    dressCodeLabel: "Código de vestimenta (opcional)", dressCodePlaceholder: "Ej: Formal de negocios",
  },
  bautizo: {
    nameLabel: "Nombre del bebé *", namePlaceholder: "Emma Sofía", fallbackName: "Tu bebé", showAge: false, showSubtitle: true,
    subtitleLabel: "Nota especial (opcional)", subtitlePlaceholder: "Con sus padrinos, Laura y Andrés",
    dressCodeLabel: "Código de vestimenta (opcional)", dressCodePlaceholder: "Ej: Formal, tonos claros",
  },
  confirmacion: {
    nameLabel: "¿Quién se confirma? *", namePlaceholder: "Juan Pablo", fallbackName: "El confirmando", showAge: false, showSubtitle: true,
    subtitleLabel: "Parroquia o nota especial (opcional)", subtitlePlaceholder: "Parroquia San Judas Tadeo · Recibe de padrino: Carlos",
    dressCodeLabel: "Código de vestimenta (opcional)", dressCodePlaceholder: "Ej: Formal",
  },
  parche: {
    nameLabel: "¿Quién arma el parche? *", namePlaceholder: "Caro y Dani", fallbackName: "El combo", showAge: false, showSubtitle: true,
    subtitleLabel: "¿Cuál es el plan? (opcional)", subtitlePlaceholder: "Tardeo en la terraza: picada, música y frías",
    dressCodeLabel: "Código de vestimenta (opcional)", dressCodePlaceholder: "Ej: Casual, trae tu mejor actitud",
  },
  reto_deportivo: {
    nameLabel: "Nombre del reto o del grupo *", namePlaceholder: "Reto 10K Amanecer", fallbackName: "El reto", showAge: false, showSubtitle: true,
    subtitleLabel: "Distancia o nivel (opcional)", subtitlePlaceholder: "10K · Ritmo suave, todos los niveles",
    dressCodeLabel: "Código de vestimenta (opcional)", dressCodePlaceholder: "Ej: Ropa deportiva cómoda",
  },
  novena: {
    nameLabel: "¿Quién ofrece la novena? *", namePlaceholder: "Familia Rodríguez", fallbackName: "La familia anfitriona",
    showAge: true, ageLabel: "¿Qué día de la novena les toca? * (1 al 9)", ageMin: 1, ageMax: 9,
    showSubtitle: true, subtitleLabel: "Nota para los invitados (opcional)", subtitlePlaceholder: "Trae tu maraca y algo pa' compartir",
    dressCodeLabel: "Código de vestimenta (opcional)", dressCodePlaceholder: "Ej: Ropa navideña, rojo y verde",
  },
};

export const THEMES = {
  videojuegos: {
    id: "videojuegos",
    name: "Videojuegos",
    emoji: "🎮",
    category: "cumple_infantil",
    dark: true,
    font: "'Press Start 2P', monospace",
    fontScale: 0.62,
    colors: { bg: "#111827", surface: "#1F2937", primary: "#22C55E", text: "#FFFFFF", accent: "#EF4444", soft: "#FBBF24" },
    image: "https://images.unsplash.com/photo-1660507224958-729c18ba1277?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🍄", "⭐", "👾", "🕹️", "🏆", "💎"],
    copy: {
      badge: (inv) => `${(inv.child_name || "").toUpperCase()}MUNDO`,
      title: (inv) => `¡${inv.child_name} sube al nivel ${inv.age}!`,
      subtitle: (inv) => inv.event_subtitle || `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "⏳ La aventura comienza en",
      details: "▼ Datos de la misión ▼",
      arrive: "🧭 Cómo llegar",
      rsvpTitle: "🎮 Registro de jugadores",
      rsvpSubtitle: "Confirma tu asistencia para reservar tu lugar en la aventura",
      confirm: "🪙 CONFIRMAR ASISTENCIA",
      successTitle: "★ ¡JUGADOR REGISTRADO! ★",
      successExtra: "+1UP 🍄",
      punctual: "¡Llega puntual, la aventura no espera!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  princesas: {
    id: "princesas",
    name: "Princesas",
    emoji: "👑",
    category: "cumple_infantil",
    dark: false,
    font: "'Dancing Script', cursive",
    fontScale: 1.25,
    colors: { bg: "#FDF2F8", surface: "#FFFFFF", primary: "#EC4899", text: "#831843", accent: "#F59E0B", soft: "#FBCFE8" },
    image: "https://images.unsplash.com/photo-1650571057388-3921855f66c9?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["👑", "🏰", "✨", "🌸", "🦋", "💖"],
    copy: {
      badge: (inv) => `Reino de ${inv.child_name}`,
      title: (inv) => `¡La princesa ${inv.child_name} cumple ${inv.age}!`,
      subtitle: (inv) => inv.event_subtitle || `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "⏳ El baile real comienza en",
      details: "✨ Detalles de la celebración real ✨",
      arrive: "🏰 Cómo llegar al castillo",
      rsvpTitle: "👑 Lista de invitados reales",
      rsvpSubtitle: "Confirma tu asistencia para reservar tu lugar en el gran baile",
      confirm: "💖 CONFIRMAR ASISTENCIA",
      successTitle: "✨ ¡INVITACIÓN REAL ACEPTADA! ✨",
      successExtra: "👑💖",
      punctual: "¡Llega puntual, la carroza no espera!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  superheroes: {
    id: "superheroes",
    name: "Superhéroes",
    emoji: "🦸",
    category: "cumple_infantil",
    dark: false,
    font: "'Bangers', cursive",
    fontScale: 1.1,
    colors: { bg: "#EFF6FF", surface: "#FFFFFF", primary: "#EF4444", text: "#1E3A8A", accent: "#EAB308", soft: "#BFDBFE" },
    image: "https://images.unsplash.com/photo-1760954185931-40d5b65fbb86?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["💥", "⚡", "🦸", "🛡️", "💫", "🌟"],
    copy: {
      badge: (inv) => `Escuadrón ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} cumple ${inv.age} y salva el día!`,
      subtitle: (inv) => inv.event_subtitle || `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "⏳ La misión heroica comienza en",
      details: "💥 Datos de la operación 💥",
      arrive: "🗺️ Cómo llegar al cuartel",
      rsvpTitle: "🦸 Reclutamiento de héroes",
      rsvpSubtitle: "Confirma tu asistencia y únete al escuadrón",
      confirm: "⚡ CONFIRMAR ASISTENCIA",
      successTitle: "💥 ¡HÉROE RECLUTADO! 💥",
      successExtra: "⚡🦸",
      punctual: "¡Llega puntual, la ciudad te necesita!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  dinosaurios: {
    id: "dinosaurios",
    name: "Dinosaurios",
    emoji: "🦖",
    category: "cumple_infantil",
    dark: false,
    font: "'Bowlby One SC', cursive",
    fontScale: 0.85,
    colors: { bg: "#F0FDF4", surface: "#FFFFFF", primary: "#16A34A", text: "#14532D", accent: "#D97706", soft: "#BBF7D0" },
    image: "https://images.unsplash.com/photo-1743600160621-144e62297185?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🦖", "🦕", "🌋", "🌿", "🥚", "🐾"],
    copy: {
      badge: (inv) => `Dinolandia de ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} cumple ${inv.age} dino-años!`,
      subtitle: (inv) => inv.event_subtitle || `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "⏳ La expedición comienza en",
      details: "🦴 Datos de la expedición 🦴",
      arrive: "🗺️ Cómo llegar al valle jurásico",
      rsvpTitle: "🦖 Registro de exploradores",
      rsvpSubtitle: "Confirma tu asistencia para unirte a la expedición",
      confirm: "🦕 CONFIRMAR ASISTENCIA",
      successTitle: "🦖 ¡EXPLORADOR REGISTRADO! 🦖",
      successExtra: "🐾🌋",
      punctual: "¡Llega puntual, los dinos no esperan!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  espacio: {
    id: "espacio",
    name: "Espacio",
    emoji: "🚀",
    category: "cumple_infantil",
    dark: true,
    font: "'Space Grotesk', sans-serif",
    fontScale: 1,
    colors: { bg: "#0F172A", surface: "#1E293B", primary: "#8B5CF6", text: "#FFFFFF", accent: "#38BDF8", soft: "#FBBF24" },
    image: "https://images.unsplash.com/photo-1656464868371-602be27fd4c2?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🚀", "🪐", "⭐", "👨‍🚀", "🛸", "🌙"],
    copy: {
      badge: (inv) => `Misión ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} despega al año ${inv.age}!`,
      subtitle: (inv) => inv.event_subtitle || `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "⏳ El despegue es en",
      details: "🛰️ Datos de la misión espacial 🛰️",
      arrive: "🧭 Coordenadas de la base",
      rsvpTitle: "🚀 Registro de astronautas",
      rsvpSubtitle: "Confirma tu asistencia para abordar la nave",
      confirm: "🛸 CONFIRMAR ASISTENCIA",
      successTitle: "⭐ ¡ASTRONAUTA A BORDO! ⭐",
      successExtra: "🚀🪐",
      punctual: "¡Llega puntual, el cohete no espera!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  unicornios: {
    id: "unicornios",
    name: "Unicornios",
    emoji: "🦄",
    category: "cumple_infantil",
    dark: false,
    font: "'Caveat Brush', cursive",
    fontScale: 1.2,
    colors: { bg: "#FAF5FF", surface: "#FFFFFF", primary: "#D946EF", text: "#4A044E", accent: "#06B6D4", soft: "#F5D0FE" },
    image: "https://images.unsplash.com/photo-1604937455095-ef2fe3d46fcd?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🦄", "🌈", "☁️", "⭐", "🍭", "💜"],
    copy: {
      badge: (inv) => `Mundo mágico de ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} cumple ${inv.age} añitos mágicos!`,
      subtitle: (inv) => inv.event_subtitle || `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "⏳ La magia comienza en",
      details: "🌈 Detalles de la fiesta mágica 🌈",
      arrive: "🗺️ Cómo llegar al arcoíris",
      rsvpTitle: "🦄 Registro de invitados mágicos",
      rsvpSubtitle: "Confirma tu asistencia para entrar al mundo mágico",
      confirm: "🌈 CONFIRMAR ASISTENCIA",
      successTitle: "🦄 ¡INVITADO MÁGICO REGISTRADO! 🦄",
      successExtra: "🌈✨",
      punctual: "¡Llega puntual, la magia no espera!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  magia: {
    id: "magia",
    name: "Sorpresa Mágica",
    emoji: "🎩",
    category: "cumple_infantil",
    dark: true,
    font: "'Cinzel Decorative', cursive",
    fontScale: 0.7,
    colors: { bg: "#170B2E", surface: "#2A1750", primary: "#A855F7", text: "#F5F3FF", accent: "#FBBF24", soft: "#C4B5FD" },
    image: "https://images.unsplash.com/photo-1703379943611-64676d5e4c96?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🎩", "🪄", "✨", "⭐", "🔮", "🎆"],
    copy: {
      badge: (inv) => `Función mágica de ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} cumple ${inv.age} años de magia!`,
      subtitle: (inv) => inv.event_subtitle || `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "🪄 El gran truco comienza en",
      details: "🔮 Detalles del espectáculo 🔮",
      arrive: "🎩 Cómo llegar al teatro mágico",
      rsvpTitle: "🪄 Registro de magos y magas",
      rsvpSubtitle: "Confirma tu asistencia para el gran truco final",
      confirm: "✨ CONFIRMAR ASISTENCIA",
      successTitle: "🎩 ¡ABRACADABRA! YA ESTÁS DENTRO 🎩",
      successExtra: "🪄✨",
      punctual: "¡Llega puntual, la magia no se repite!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  circo: {
    id: "circo",
    name: "Circo",
    emoji: "🎪",
    category: "cumple_infantil",
    dark: false,
    font: "'Bungee', cursive",
    fontScale: 0.75,
    colors: { bg: "#FFF9E6", surface: "#FFFFFF", primary: "#DC2626", text: "#7C2D12", accent: "#EAB308", soft: "#FEF3C7" },
    image: "https://images.unsplash.com/photo-1558180227-93c31d143df3?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🎪", "🎡", "🍿", "🎈", "🤹", "🦁"],
    copy: {
      badge: (inv) => `Gran Carpa de ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} cumple ${inv.age} bajo la carpa!`,
      subtitle: (inv) => inv.event_subtitle || `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "🎪 La función empieza en",
      details: "🎟️ Detalles de la función 🎟️",
      arrive: "🗺️ Cómo llegar a la carpa",
      rsvpTitle: "🤹 Registro de artistas",
      rsvpSubtitle: "Confirma tu asistencia para el mejor show del año",
      confirm: "🎟️ CONFIRMAR ASISTENCIA",
      successTitle: "🎪 ¡ENTRADA CONFIRMADA! 🎪",
      successExtra: "🎡🍿",
      punctual: "¡Llega puntual, la función no espera!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  piratas: {
    id: "piratas",
    name: "Piratas",
    emoji: "🏴‍☠️",
    category: "cumple_infantil",
    dark: true,
    font: "'Pirata One', cursive",
    fontScale: 1.3,
    colors: { bg: "#0C2340", surface: "#163A5F", primary: "#D97706", text: "#FEF3C7", accent: "#F87171", soft: "#93C5FD" },
    image: "https://images.unsplash.com/photo-1668816102414-8b3a0f33107d?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🏴‍☠️", "⚓", "🗺️", "💰", "🦜", "⛵"],
    copy: {
      badge: (inv) => `Tripulación de ${inv.child_name}`,
      title: (inv) => `¡Capitán ${inv.child_name} cumple ${inv.age} años!`,
      subtitle: (inv) => inv.event_subtitle || `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "⚓ Zarpamos en",
      details: "🗺️ Datos del tesoro 🗺️",
      arrive: "🧭 Cómo llegar al puerto",
      rsvpTitle: "🏴‍☠️ Alistamiento de la tripulación",
      rsvpSubtitle: "Confirma tu asistencia para zarpar rumbo a la aventura",
      confirm: "💰 CONFIRMAR ASISTENCIA",
      successTitle: "⚓ ¡A BORDO, GRUMETE! ⚓",
      successExtra: "🏴‍☠️💰",
      punctual: "¡Llega puntual, el barco zarpa sin avisar!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  sirenas: {
    id: "sirenas",
    name: "Sirenas",
    emoji: "🧜‍♀️",
    category: "cumple_infantil",
    dark: false,
    font: "'Comfortaa', cursive",
    fontScale: 0.95,
    colors: { bg: "#ECFEFF", surface: "#FFFFFF", primary: "#0891B2", text: "#164E63", accent: "#F472B6", soft: "#A5F3FC" },
    image: "https://images.unsplash.com/photo-1533431557381-51a6546cf7ce?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🧜‍♀️", "🐚", "🫧", "🐠", "🌊", "⭐"],
    copy: {
      badge: (inv) => `Reino submarino de ${inv.child_name}`,
      title: (inv) => `¡La sirena ${inv.child_name} cumple ${inv.age} años!`,
      subtitle: (inv) => inv.event_subtitle || `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "🫧 La aventura submarina empieza en",
      details: "🐚 Detalles del arrecife 🐚",
      arrive: "🌊 Cómo llegar al océano",
      rsvpTitle: "🧜‍♀️ Registro de sirenas y tritones",
      rsvpSubtitle: "Confirma tu asistencia para nadar en la fiesta",
      confirm: "🐚 CONFIRMAR ASISTENCIA",
      successTitle: "🌊 ¡YA ERES PARTE DEL ARRECIFE! 🌊",
      successExtra: "🧜‍♀️🐠",
      punctual: "¡Llega puntual, la marea no espera!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  safari: {
    id: "safari",
    name: "Safari",
    emoji: "🦁",
    category: "cumple_infantil",
    dark: false,
    font: "'Baloo 2', cursive",
    fontScale: 0.95,
    colors: { bg: "#FFF7ED", surface: "#FFFFFF", primary: "#B45309", text: "#422006", accent: "#16A34A", soft: "#FDE68A" },
    image: "https://images.unsplash.com/photo-1754424578467-7c219061e45e?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🦁", "🐘", "🦒", "🌿", "🐾", "🌅"],
    copy: {
      badge: (inv) => `Safari de ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} cumple ${inv.age} años en la sabana!`,
      subtitle: (inv) => inv.event_subtitle || `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "🐾 La expedición safari sale en",
      details: "🌍 Datos de la expedición 🌍",
      arrive: "🗺️ Cómo llegar al safari",
      rsvpTitle: "🦁 Registro de exploradores",
      rsvpSubtitle: "Confirma tu asistencia para la aventura en la sabana",
      confirm: "🐘 CONFIRMAR ASISTENCIA",
      successTitle: "🦒 ¡EXPLORADOR LISTO PARA EL SAFARI! 🦒",
      successExtra: "🦁🌿",
      punctual: "¡Llega puntual, la manada no espera!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  granja: {
    id: "granja",
    name: "Granja",
    emoji: "🐮",
    category: "cumple_infantil",
    dark: false,
    font: "'Chewy', cursive",
    fontScale: 0.95,
    colors: { bg: "#FFFBEB", surface: "#FFFFFF", primary: "#CA8A04", text: "#713F12", accent: "#DC2626", soft: "#FEF08A" },
    image: "https://images.unsplash.com/photo-1768392927049-f0d92490fb5f?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🐮", "🐑", "🐔", "🐷", "🌾", "🚜"],
    copy: {
      badge: (inv) => `Granja de ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} cumple ${inv.age} añitos en la granja!`,
      subtitle: (inv) => inv.event_subtitle || `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "🚜 El paseo por la granja empieza en",
      details: "🌾 Detalles del corral 🌾",
      arrive: "🗺️ Cómo llegar a la granja",
      rsvpTitle: "🐮 Registro de granjeritos",
      rsvpSubtitle: "Confirma tu asistencia para dar de comer a los animalitos",
      confirm: "🐔 CONFIRMAR ASISTENCIA",
      successTitle: "🐷 ¡YA ERES PARTE DE LA GRANJA! 🐷",
      successExtra: "🐮🌾",
      punctual: "¡Llega puntual, el gallo ya cantó!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  fiesta_adultos: {
    id: "fiesta_adultos",
    name: "Fiesta Elegante",
    emoji: "🥂",
    category: "cumple_adulto",
    dark: true,
    font: "'Poiret One', cursive",
    fontScale: 1.15,
    colors: { bg: "#0D0D0D", surface: "#1A1A1A", primary: "#D4AF37", text: "#F5F5F5", accent: "#E11D48", soft: "#C9A94F" },
    image: "https://images.unsplash.com/photo-1647905555465-0f9004fbdaed?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🥂", "🎉", "✨", "🎷", "🍾", "🌟"],
    copy: {
      badge: (inv) => `Fiesta de ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} cumple ${inv.age}!`,
      subtitle: (inv) => inv.event_subtitle || `UNA NOCHE PARA CELEBRAR 🥂`,
      countdown: "🕰️ La fiesta comienza en",
      details: "🍾 Detalles del evento 🍾",
      arrive: "🗺️ Cómo llegar",
      rsvpTitle: "🥂 Confirma tu asistencia",
      rsvpSubtitle: "Reserva tu lugar para brindar juntos",
      confirm: "🎉 CONFIRMAR ASISTENCIA",
      successTitle: "🥂 ¡NOS VEMOS EN LA FIESTA! 🥂",
      successExtra: "🎉✨",
      punctual: "La elegancia también es puntualidad",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  boda: {
    id: "boda",
    name: "Boda Elegante",
    emoji: "💍",
    category: "boda",
    dark: false,
    font: "'Great Vibes', cursive",
    fontScale: 1.4,
    colors: { bg: "#FFFBF5", surface: "#FFFFFF", primary: "#A88763", text: "#3D2C1E", accent: "#D4AF37", soft: "#F1E4D0" },
    image: "https://images.unsplash.com/photo-1494955870715-979ca4f13bf0?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["💍", "👰", "🤵", "🥂", "🌹", "✨"],
    copy: {
      badge: (inv) => `${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} nos casamos! 💍`,
      subtitle: (inv) => inv.event_subtitle || "Acompáñanos a celebrar nuestro amor",
      countdown: "💕 Nuestra boda es en",
      details: "🥂 Detalles de la celebración 🥂",
      arrive: "🗺️ Cómo llegar",
      rsvpTitle: "💍 Confirma tu asistencia",
      rsvpSubtitle: "Nos encantaría contar contigo en este día tan especial",
      confirm: "🌹 CONFIRMAR ASISTENCIA",
      successTitle: "💍 ¡GRACIAS POR CONFIRMAR! 💍",
      successExtra: "🥂✨",
      punctual: "Te esperamos puntuales para comenzar la celebración",
      msgLabel: () => `Mensaje para los novios (opcional)`,
    },
  },
  mundial: {
    id: "mundial",
    name: "Ver el Partido",
    emoji: "⚽",
    category: "partido",
    dark: true,
    font: "'Anton', sans-serif",
    fontScale: 0.95,
    colors: { bg: "#0B1F0F", surface: "#132B18", primary: "#22C55E", text: "#FFFFFF", accent: "#FBBF24", soft: "#86EFAC" },
    image: "https://images.unsplash.com/photo-1549333580-4cb2c5c8e421?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["⚽", "🏆", "📣", "🎊", "🥅", "👕"],
    copy: {
      badge: (inv) => `¡Partidazo con ${inv.child_name}!`,
      title: (inv) => `¡${inv.child_name} te invita a ver el partido! ⚽`,
      subtitle: (inv) => inv.event_subtitle || "¡No te lo pierdas! 🎉",
      countdown: "⏱️ El pitazo inicial es en",
      details: "📋 Detalles del partido 📋",
      arrive: "🗺️ Cómo llegar",
      rsvpTitle: "⚽ Confirma tu lugar en la tribuna",
      rsvpSubtitle: "Dinos si vienes a alentar con nosotros",
      confirm: "🎉 CONFIRMAR ASISTENCIA",
      successTitle: "🏆 ¡GOOOL! YA ESTÁS EN LA LISTA 🏆",
      successExtra: "⚽🎉",
      punctual: "¡Llega antes del pitazo inicial!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  cumbre: {
    id: "cumbre",
    name: "Cumbre Ejecutiva",
    emoji: "🎤",
    category: "conferencia",
    dark: true,
    font: "'Sora', sans-serif",
    fontScale: 1,
    colors: { bg: "#0B1220", surface: "#141E33", primary: "#5B9DFF", text: "#F2F6FC", accent: "#E9C46A", soft: "#A9C7FF" },
    image: "https://images.unsplash.com/photo-1758550445758-165aeab5b26e?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🎤", "💼", "🤝", "📊", "🏙️", "✨"],
    copy: {
      badge: (inv) => `${inv.child_name} · Acceso preferencial`,
      title: (inv) => `${inv.child_name}`,
      subtitle: (inv) => inv.event_subtitle || "Conocimiento, networking y grandes conversaciones",
      countdown: "🕘 El evento comienza en",
      details: "📋 Agenda y detalles 📋",
      arrive: "📍 Cómo llegar a la sede",
      rsvpTitle: "🤝 Reserva tu cupo",
      rsvpSubtitle: "Los cupos son limitados, confirma tu registro hoy",
      confirm: "✅ CONFIRMAR REGISTRO",
      successTitle: "🎫 ¡REGISTRO EXITOSO! NOS VEMOS ALLÁ 🎫",
      successExtra: "🤝📊",
      punctual: "Llega 15 minutos antes para tu acreditación en recepción",
      msgLabel: () => `Mensaje o pregunta para los organizadores (opcional)`,
    },
  },
  cielito: {
    id: "cielito",
    name: "Cielito de Algodón",
    emoji: "🕊️",
    category: "bautizo",
    dark: false,
    font: "'Sacramento', cursive",
    fontScale: 1.35,
    colors: { bg: "#F3F9FE", surface: "#FFFFFF", primary: "#4A8CC7", text: "#2B4A66", accent: "#F2C186", soft: "#DCEBF9" },
    image: "https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🕊️", "👼", "☁️", "💧", "🌟", "🤍"],
    copy: {
      badge: (inv) => `El bautizo de ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} recibe las aguas del bautismo! 🕊️`,
      subtitle: (inv) => inv.event_subtitle || "Una bendición que queremos compartir contigo 🤍",
      countdown: "☁️ La bendición llega en",
      details: "📖 Detalles de la ceremonia 📖",
      arrive: "🗺️ Cómo llegar a la iglesia",
      rsvpTitle: "🤍 Acompáñanos en este día de gracia",
      rsvpSubtitle: "Confirma tu asistencia, tu presencia es la mejor bendición",
      confirm: "🕊️ CONFIRMAR ASISTENCIA",
      successTitle: "👼 ¡GRACIAS POR ACOMPAÑARNOS! 👼",
      successExtra: "🕊️☁️",
      punctual: "La ceremonia empieza en punto, te esperamos en la iglesia",
      msgLabel: (inv) => `Bendiciones y deseos para ${inv.child_name} (opcional)`,
    },
  },
  llama_viva: {
    id: "llama_viva",
    name: "Llama Viva",
    emoji: "🔥",
    category: "confirmacion",
    dark: false,
    font: "'Cormorant Garamond', serif",
    fontScale: 1.15,
    colors: { bg: "#FBF6EE", surface: "#FFFFFF", primary: "#8C2F3F", text: "#3A2328", accent: "#C79A3F", soft: "#F1E0D6" },
    image: "https://images.unsplash.com/photo-1637501357872-a5b339a3eb01?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["✝️", "🕊️", "🔥", "📖", "🌿", "✨"],
    copy: {
      badge: (inv) => `Confirmación de ${inv.child_name}`,
      title: (inv) => `${inv.child_name} confirma su fe ✝️`,
      subtitle: (inv) => inv.event_subtitle || "Un paso grande en su camino, y queremos celebrarlo contigo",
      countdown: "🕊️ El gran paso llega en",
      details: "🕯️ Detalles de la ceremonia y la celebración 🕯️",
      arrive: "🗺️ Cómo llegar a la parroquia",
      rsvpTitle: "✝️ Ahora el que confirma eres tú",
      rsvpSubtitle: "Dinos si nos acompañas en este día de fe y familia",
      confirm: "🕊️ CONFIRMAR ASISTENCIA",
      successTitle: "✨ ¡CONFIRMADÍSIMO! GRACIAS POR ACOMPAÑARNOS ✨",
      successExtra: "✝️🕊️",
      punctual: "Llega antes de que empiece la misa, el sacramento no espera",
      msgLabel: (inv) => `Palabras de aliento para ${inv.child_name} (opcional)`,
    },
  },
  tardeo: {
    id: "tardeo",
    name: "Tardeo Dorado",
    emoji: "🌇",
    category: "parche",
    dark: true,
    font: "'Lilita One', sans-serif",
    fontScale: 0.85,
    colors: { bg: "#1C1033", surface: "#2A1B4D", primary: "#FF6B4A", text: "#FFF6EC", accent: "#FFC94B", soft: "#FFB39E" },
    image: "https://images.unsplash.com/photo-1758272133483-281d50324455?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🍻", "🌇", "😎", "🎶", "🍕", "🥂"],
    copy: {
      badge: (inv) => `¡${inv.child_name} armó parche!`,
      title: (inv) => `¡${inv.child_name} te invita al parche! 🍻`,
      subtitle: (inv) => inv.event_subtitle || "Deja la pereza y apúntate 😎",
      countdown: "⏰ El parche arranca en",
      details: "📋 Los datos del plan 📋",
      arrive: "🗺️ Cómo caer al punto",
      rsvpTitle: "🍻 ¿Te apuntas o qué?",
      rsvpSubtitle: "Confirma pa' saber cuántas sillas y cuántas frías pedimos",
      confirm: "😎 ¡DE UNA, ME APUNTO!",
      successTitle: "🎉 ¡QUEDASTE EN EL PARCHE! 🎉",
      successExtra: "🍻😎",
      punctual: "Llega temprano que los mejores puestos vuelan",
      msgLabel: (inv) => `Déjale una nota a ${inv.child_name} (opcional)`,
    },
  },
  gloria: {
    id: "gloria",
    name: "Sudor y Gloria",
    emoji: "🏅",
    category: "reto_deportivo",
    dark: true,
    font: "'Russo One', sans-serif",
    fontScale: 0.8,
    colors: { bg: "#0C1114", surface: "#151C21", primary: "#C9F53F", text: "#F2F7F2", accent: "#FF8534", soft: "#E7FBAA" },
    image: "https://images.unsplash.com/photo-1526676317768-d9b14f15615a?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🏃", "💦", "⏱️", "👟", "🔥", "🏅"],
    copy: {
      badge: (inv) => `${inv.child_name} · ¡Nadie se raja!`,
      title: (inv) => `¡${inv.child_name}! ¿Te le mides? 🏃💨`,
      subtitle: (inv) => inv.event_subtitle || "Sin excusas: el sofá puede esperar 💪",
      countdown: "⏱️ La salida es en",
      details: "📋 Detalles del reto 📋",
      arrive: "📍 Punto de encuentro",
      rsvpTitle: "👟 Inscríbete al reto",
      rsvpSubtitle: "Confirma tu cupo y ve alistando esos tenis",
      confirm: "🔥 ¡ME LE MIDO!",
      successTitle: "🏅 ¡INSCRITO! NOS VEMOS EN LA LÍNEA DE SALIDA 🏅",
      successExtra: "🏃💦",
      punctual: "Llega 15 minutos antes para calentar con el grupo",
      msgLabel: () => `Mensaje para el grupo (opcional)`,
    },
  },
  aguinaldos: {
    id: "aguinaldos",
    name: "Luces de Diciembre",
    emoji: "🕯️",
    category: "novena",
    dark: true,
    font: "'Mountains of Christmas', cursive",
    fontScale: 1.1,
    colors: { bg: "#12271B", surface: "#1D3A28", primary: "#E0524A", text: "#FFF7E6", accent: "#F4C04F", soft: "#A9D8B8" },
    image: "https://images.unsplash.com/photo-1766422646104-49661299db4b?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🎄", "⭐", "🕯️", "🎶", "🎁", "✨"],
    copy: {
      badge: (inv) => `Novena donde ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} te espera para el día ${inv.age} de la novena! 🎄`,
      subtitle: (inv) => inv.event_subtitle || "Con natilla, buñuelos y villancicos 🎶",
      countdown: "⭐ Los villancicos empiezan en",
      details: "🎄 Detalles de la novena 🎄",
      arrive: "🗺️ Cómo llegar a la casa",
      rsvpTitle: "🎶 Apúntate a cantar los gozos",
      rsvpSubtitle: "Confirma pa' que alcance la natilla y los buñuelos",
      confirm: "🎄 ¡ALLÁ ESTARÉ!",
      successTitle: "⭐ ¡CONFIRMADO! TE GUARDAMOS BUÑUELO ⭐",
      successExtra: "🎄🕯️",
      punctual: "Llega antes de los gozos, que la novena empieza en punto",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
};

export const THEME_LIST = Object.values(THEMES);

// Curated color palettes the guest-organizer can pick instead of the theme's
// default primary/accent/soft. "" (id empty string) means "use the theme's
// own colors" — the default for every invitation, so this is purely additive.
// Only these three tokens are overridable: bg/surface/text/dark stay tied to
// the theme so contrast and light/dark legibility are never at risk.
export const PALETTES = [
  { id: "dorado", name: "Dorado clásico", primary: "#A88763", accent: "#D4AF37", soft: "#F1E4D0" },
  { id: "azul_noche", name: "Azul noche", primary: "#2C3E63", accent: "#5B9DFF", soft: "#A9C7FF" },
  { id: "rosa_cuarzo", name: "Rosa cuarzo", primary: "#B8748A", accent: "#E8A6BC", soft: "#F5D9E3" },
  { id: "verde_salvia", name: "Verde salvia", primary: "#6B8068", accent: "#A3B899", soft: "#E1E8DA" },
  { id: "terracota", name: "Terracota", primary: "#B5654A", accent: "#E0956B", soft: "#F2D9C8" },
  { id: "lavanda", name: "Lavanda", primary: "#7C6A96", accent: "#B4A3D1", soft: "#E8E1F2" },
  { id: "vino", name: "Vino tinto", primary: "#6E2A3A", accent: "#B0435C", soft: "#E8C4CC" },
  { id: "esmeralda", name: "Esmeralda", primary: "#1F6650", accent: "#3FA285", soft: "#C8E8DD" },
];
export const PALETTE_MAP = Object.fromEntries(PALETTES.map((p) => [p.id, p]));

// Curated typefaces the guest-organizer can pick instead of the theme's default
// --inv-font. "" means "use the theme's own font". Every face here is already
// loaded by the Google Fonts @import at the top of App.css, so picking one never
// costs an extra network request. Kept to elegant/formal faces since this picker
// only appears for the nine "grown-up" categories.
export const FONTS = [
  { id: "playfair", name: "Playfair Display", css: "'Playfair Display', serif" },
  { id: "cormorant", name: "Cormorant Garamond", css: "'Cormorant Garamond', serif" },
  { id: "cinzel", name: "Cinzel Decorative", css: "'Cinzel Decorative', serif" },
  { id: "great_vibes", name: "Great Vibes", css: "'Great Vibes', cursive" },
  { id: "sacramento", name: "Sacramento", css: "'Sacramento', cursive" },
  { id: "dancing_script", name: "Dancing Script", css: "'Dancing Script', cursive" },
  { id: "montserrat", name: "Montserrat", css: "'Montserrat', sans-serif" },
  { id: "sora", name: "Sora", css: "'Sora', sans-serif" },
  { id: "poiret", name: "Poiret One", css: "'Poiret One', sans-serif" },
];
export const FONT_MAP = Object.fromEntries(FONTS.map((f) => [f.id, f]));

// Categories that render the dark glassmorphic InvitationHeroElegant cover (+ the quick-info
// card right under it, + the font/dress-code pickers in the builder) instead of the plain
// .inv-hero header. Shared between InvitationView.jsx (what to render) and Builder.jsx
// (which optional fields to show while editing).
export const ELEGANT_HERO_CATEGORIES = new Set([
  "boda", "cumple_adulto", "conferencia", "bautizo", "confirmacion", "novena",
  "partido", "parche", "reto_deportivo",
]);
export const ELEGANT_REVEAL_CATEGORIES = new Set(["boda", "cumple_adulto"]);

// All theme copy (title/badge/subtitle/section headers/button labels/decorations) ships
// with emoji baked in by design. When an invitation has show_emojis === false, every piece
// of copy is run through this before rendering. Covers: \p{Extended_Pictographic} (most
// emoji), \p{Regional_Indicator} (flag emoji like 🇨🇴, built from letter-pairs — not
// covered by Extended_Pictographic), \p{Emoji_Modifier} (skin-tone modifiers), and the
// ZWJ/variation-selector glue characters that stitch compound emoji (👨‍👩‍👧) together —
// without those, removing the pictographs alone leaves the invisible glue behind. The
// final replace collapses the double space left where a removed emoji sat between words
// (theme copy uses both "🎉 Texto" and "Texto 🎉" patterns).
const EMOJI_RE = /[\p{Extended_Pictographic}\p{Emoji_Modifier}\p{Regional_Indicator}‍️]/gu;
export function stripEmojis(text) {
  if (!text) return text;
  return String(text).replace(EMOJI_RE, "").replace(/ {2,}/g, " ").trim();
}

export function formatDateEs(dateStr) {
  if (!dateStr) return "";
  const [y, m, d] = dateStr.split("-").map(Number);
  const date = new Date(y, m - 1, d);
  const s = date.toLocaleDateString("es-CO", { weekday: "long", day: "numeric", month: "long", year: "numeric" });
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export function formatTimeEs(timeStr) {
  if (!timeStr) return "";
  const [h, min] = timeStr.split(":").map(Number);
  const period = h < 12 ? "de la mañana" : h < 19 ? "de la tarde" : "de la noche";
  const h12 = h % 12 === 0 ? 12 : h % 12;
  return `${h12}:${String(min).padStart(2, "0")} ${period}`;
}

export function calendarUrl(inv) {
  if (!inv.event_date || !inv.event_time) return "#";
  const start = `${inv.event_date.replace(/-/g, "")}T${inv.event_time.replace(":", "")}00`;
  const [h, m] = inv.event_time.split(":").map(Number);
  const endH = Math.min(h + 4, 23);
  const end = `${inv.event_date.replace(/-/g, "")}T${String(endH).padStart(2, "0")}${String(m).padStart(2, "0")}00`;
  const params = new URLSearchParams({
    action: "TEMPLATE",
    text: `${inv.child_name || "Evento"} 🎉`,
    dates: `${start}/${end}`,
    details: `${inv.child_full_name || inv.child_name || ""}`,
    location: `${inv.venue}${inv.address ? ", " + inv.address : ""}`,
  });
  return `https://www.google.com/calendar/render?${params.toString()}`;
}

export function whatsappUrl(inv) {
  if (!inv.whatsapp) return null;
  const num = inv.whatsapp.replace(/\D/g, "");
  const text = encodeURIComponent(
    `¡Hola! Confirmo mi asistencia al evento de ${inv.child_name} 🎉 el ${formatDateEs(inv.event_date)}. Somos: `
  );
  return `https://wa.me/${num}?text=${text}`;
}
