export const CATEGORIES = [
  { id: "cumple_infantil", name: "Cumpleaños infantil", emoji: "🎈" },
  { id: "cumple_adulto", name: "Cumpleaños de adultos", emoji: "🥳" },
  { id: "boda", name: "Bodas", emoji: "💍" },
  { id: "partido", name: "Ver el partido", emoji: "⚽" },
];

// Per-category field labels/placeholders and fallback display name, shared by
// Builder.jsx (creation form) and AdminVentas.jsx (manual creation form).
export const CATEGORY_FIELDS = {
  cumple_infantil: { nameLabel: "Nombre del peque *", namePlaceholder: "Gabriel", fallbackName: "Tu peque", showAge: true, ageLabel: "Edad que cumple *", showSubtitle: false },
  cumple_adulto: { nameLabel: "Nombre del festejado *", namePlaceholder: "Andrea", fallbackName: "El festejado", showAge: true, ageLabel: "Edad que cumple *", showSubtitle: false },
  boda: {
    nameLabel: "Nombres de los novios *", namePlaceholder: "Juan & María", fallbackName: "Los novios", showAge: false, showSubtitle: true,
    subtitleLabel: "Detalle especial (opcional)", subtitlePlaceholder: "Ceremonia religiosa seguida de recepción",
  },
  partido: {
    nameLabel: "¿Quién invita? *", namePlaceholder: "Andrés", fallbackName: "El anfitrión", showAge: false, showSubtitle: true,
    subtitleLabel: "¿Qué partido? (opcional)", subtitlePlaceholder: "Colombia 🇨🇴 vs Argentina 🇦🇷",
  },
};

export const THEMES = {
  videojuegos: {
    id: "videojuegos",
    name: "Videojuegos",
    emoji: "🎮",
    category: "cumple_infantil",
    dark: true,
    font: "'Press Start 2P', monospace",
    fontScale: 0.62,
    colors: { bg: "#111827", surface: "#1F2937", primary: "#22C55E", text: "#FFFFFF", accent: "#EF4444", soft: "#FBBF24" },
    image: "https://images.unsplash.com/photo-1660507224958-729c18ba1277?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🍄", "⭐", "👾", "🕹️", "🏆", "💎"],
    copy: {
      badge: (inv) => `${(inv.child_name || "").toUpperCase()}MUNDO`,
      title: (inv) => `¡${inv.child_name} sube al nivel ${inv.age}!`,
      subtitle: (inv) => `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "⏳ La aventura comienza en",
      details: "▼ Datos de la misión ▼",
      arrive: "🧭 Cómo llegar",
      rsvpTitle: "🎮 Registro de jugadores",
      rsvpSubtitle: "Confirma tu asistencia para reservar tu lugar en la aventura",
      confirm: "🪙 CONFIRMAR ASISTENCIA",
      successTitle: "★ ¡JUGADOR REGISTRADO! ★",
      successExtra: "+1UP 🍄",
      punctual: "¡Llega puntual, la aventura no espera!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  princesas: {
    id: "princesas",
    name: "Princesas",
    emoji: "👑",
    category: "cumple_infantil",
    dark: false,
    font: "'Dancing Script', cursive",
    fontScale: 1.25,
    colors: { bg: "#FDF2F8", surface: "#FFFFFF", primary: "#EC4899", text: "#831843", accent: "#F59E0B", soft: "#FBCFE8" },
    image: "https://images.unsplash.com/photo-1650571057388-3921855f66c9?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["👑", "🏰", "✨", "🌸", "🦋", "💖"],
    copy: {
      badge: (inv) => `Reino de ${inv.child_name}`,
      title: (inv) => `¡La princesa ${inv.child_name} cumple ${inv.age}!`,
      subtitle: (inv) => `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "⏳ El baile real comienza en",
      details: "✨ Detalles de la celebración real ✨",
      arrive: "🏰 Cómo llegar al castillo",
      rsvpTitle: "👑 Lista de invitados reales",
      rsvpSubtitle: "Confirma tu asistencia para reservar tu lugar en el gran baile",
      confirm: "💖 CONFIRMAR ASISTENCIA",
      successTitle: "✨ ¡INVITACIÓN REAL ACEPTADA! ✨",
      successExtra: "👑💖",
      punctual: "¡Llega puntual, la carroza no espera!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  superheroes: {
    id: "superheroes",
    name: "Superhéroes",
    emoji: "🦸",
    category: "cumple_infantil",
    dark: false,
    font: "'Bangers', cursive",
    fontScale: 1.1,
    colors: { bg: "#EFF6FF", surface: "#FFFFFF", primary: "#EF4444", text: "#1E3A8A", accent: "#EAB308", soft: "#BFDBFE" },
    image: "https://images.unsplash.com/photo-1760954185931-40d5b65fbb86?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["💥", "⚡", "🦸", "🛡️", "💫", "🌟"],
    copy: {
      badge: (inv) => `Escuadrón ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} cumple ${inv.age} y salva el día!`,
      subtitle: (inv) => `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "⏳ La misión heroica comienza en",
      details: "💥 Datos de la operación 💥",
      arrive: "🗺️ Cómo llegar al cuartel",
      rsvpTitle: "🦸 Reclutamiento de héroes",
      rsvpSubtitle: "Confirma tu asistencia y únete al escuadrón",
      confirm: "⚡ CONFIRMAR ASISTENCIA",
      successTitle: "💥 ¡HÉROE RECLUTADO! 💥",
      successExtra: "⚡🦸",
      punctual: "¡Llega puntual, la ciudad te necesita!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  dinosaurios: {
    id: "dinosaurios",
    name: "Dinosaurios",
    emoji: "🦖",
    category: "cumple_infantil",
    dark: false,
    font: "'Bowlby One SC', cursive",
    fontScale: 0.85,
    colors: { bg: "#F0FDF4", surface: "#FFFFFF", primary: "#16A34A", text: "#14532D", accent: "#D97706", soft: "#BBF7D0" },
    image: "https://images.unsplash.com/photo-1743600160621-144e62297185?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🦖", "🦕", "🌋", "🌿", "🥚", "🐾"],
    copy: {
      badge: (inv) => `Dinolandia de ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} cumple ${inv.age} dino-años!`,
      subtitle: (inv) => `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "⏳ La expedición comienza en",
      details: "🦴 Datos de la expedición 🦴",
      arrive: "🗺️ Cómo llegar al valle jurásico",
      rsvpTitle: "🦖 Registro de exploradores",
      rsvpSubtitle: "Confirma tu asistencia para unirte a la expedición",
      confirm: "🦕 CONFIRMAR ASISTENCIA",
      successTitle: "🦖 ¡EXPLORADOR REGISTRADO! 🦖",
      successExtra: "🐾🌋",
      punctual: "¡Llega puntual, los dinos no esperan!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  espacio: {
    id: "espacio",
    name: "Espacio",
    emoji: "🚀",
    category: "cumple_infantil",
    dark: true,
    font: "'Space Grotesk', sans-serif",
    fontScale: 1,
    colors: { bg: "#0F172A", surface: "#1E293B", primary: "#8B5CF6", text: "#FFFFFF", accent: "#38BDF8", soft: "#FBBF24" },
    image: "https://images.unsplash.com/photo-1656464868371-602be27fd4c2?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🚀", "🪐", "⭐", "👨‍🚀", "🛸", "🌙"],
    copy: {
      badge: (inv) => `Misión ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} despega al año ${inv.age}!`,
      subtitle: (inv) => `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "⏳ El despegue es en",
      details: "🛰️ Datos de la misión espacial 🛰️",
      arrive: "🧭 Coordenadas de la base",
      rsvpTitle: "🚀 Registro de astronautas",
      rsvpSubtitle: "Confirma tu asistencia para abordar la nave",
      confirm: "🛸 CONFIRMAR ASISTENCIA",
      successTitle: "⭐ ¡ASTRONAUTA A BORDO! ⭐",
      successExtra: "🚀🪐",
      punctual: "¡Llega puntual, el cohete no espera!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  unicornios: {
    id: "unicornios",
    name: "Unicornios",
    emoji: "🦄",
    category: "cumple_infantil",
    dark: false,
    font: "'Caveat Brush', cursive",
    fontScale: 1.2,
    colors: { bg: "#FAF5FF", surface: "#FFFFFF", primary: "#D946EF", text: "#4A044E", accent: "#06B6D4", soft: "#F5D0FE" },
    image: "https://images.unsplash.com/photo-1604937455095-ef2fe3d46fcd?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🦄", "🌈", "☁️", "⭐", "🍭", "💜"],
    copy: {
      badge: (inv) => `Mundo mágico de ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} cumple ${inv.age} añitos mágicos!`,
      subtitle: (inv) => `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "⏳ La magia comienza en",
      details: "🌈 Detalles de la fiesta mágica 🌈",
      arrive: "🗺️ Cómo llegar al arcoíris",
      rsvpTitle: "🦄 Registro de invitados mágicos",
      rsvpSubtitle: "Confirma tu asistencia para entrar al mundo mágico",
      confirm: "🌈 CONFIRMAR ASISTENCIA",
      successTitle: "🦄 ¡INVITADO MÁGICO REGISTRADO! 🦄",
      successExtra: "🌈✨",
      punctual: "¡Llega puntual, la magia no espera!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  magia: {
    id: "magia",
    name: "Sorpresa Mágica",
    emoji: "🎩",
    category: "cumple_infantil",
    dark: true,
    font: "'Cinzel Decorative', cursive",
    fontScale: 0.7,
    colors: { bg: "#170B2E", surface: "#2A1750", primary: "#A855F7", text: "#F5F3FF", accent: "#FBBF24", soft: "#C4B5FD" },
    image: "https://images.unsplash.com/photo-1703379943611-64676d5e4c96?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🎩", "🪄", "✨", "⭐", "🔮", "🎆"],
    copy: {
      badge: (inv) => `Función mágica de ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} cumple ${inv.age} años de magia!`,
      subtitle: (inv) => `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "🪄 El gran truco comienza en",
      details: "🔮 Detalles del espectáculo 🔮",
      arrive: "🎩 Cómo llegar al teatro mágico",
      rsvpTitle: "🪄 Registro de magos y magas",
      rsvpSubtitle: "Confirma tu asistencia para el gran truco final",
      confirm: "✨ CONFIRMAR ASISTENCIA",
      successTitle: "🎩 ¡ABRACADABRA! YA ESTÁS DENTRO 🎩",
      successExtra: "🪄✨",
      punctual: "¡Llega puntual, la magia no se repite!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  circo: {
    id: "circo",
    name: "Circo",
    emoji: "🎪",
    category: "cumple_infantil",
    dark: false,
    font: "'Bungee', cursive",
    fontScale: 0.75,
    colors: { bg: "#FFF9E6", surface: "#FFFFFF", primary: "#DC2626", text: "#7C2D12", accent: "#EAB308", soft: "#FEF3C7" },
    image: "https://images.unsplash.com/photo-1558180227-93c31d143df3?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🎪", "🎡", "🍿", "🎈", "🤹", "🦁"],
    copy: {
      badge: (inv) => `Gran Carpa de ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} cumple ${inv.age} bajo la carpa!`,
      subtitle: (inv) => `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "🎪 La función empieza en",
      details: "🎟️ Detalles de la función 🎟️",
      arrive: "🗺️ Cómo llegar a la carpa",
      rsvpTitle: "🤹 Registro de artistas",
      rsvpSubtitle: "Confirma tu asistencia para el mejor show del año",
      confirm: "🎟️ CONFIRMAR ASISTENCIA",
      successTitle: "🎪 ¡ENTRADA CONFIRMADA! 🎪",
      successExtra: "🎡🍿",
      punctual: "¡Llega puntual, la función no espera!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  piratas: {
    id: "piratas",
    name: "Piratas",
    emoji: "🏴‍☠️",
    category: "cumple_infantil",
    dark: true,
    font: "'Pirata One', cursive",
    fontScale: 1.3,
    colors: { bg: "#0C2340", surface: "#163A5F", primary: "#D97706", text: "#FEF3C7", accent: "#F87171", soft: "#93C5FD" },
    image: "https://images.unsplash.com/photo-1668816102414-8b3a0f33107d?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🏴‍☠️", "⚓", "🗺️", "💰", "🦜", "⛵"],
    copy: {
      badge: (inv) => `Tripulación de ${inv.child_name}`,
      title: (inv) => `¡Capitán ${inv.child_name} cumple ${inv.age} años!`,
      subtitle: (inv) => `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "⚓ Zarpamos en",
      details: "🗺️ Datos del tesoro 🗺️",
      arrive: "🧭 Cómo llegar al puerto",
      rsvpTitle: "🏴‍☠️ Alistamiento de la tripulación",
      rsvpSubtitle: "Confirma tu asistencia para zarpar rumbo a la aventura",
      confirm: "💰 CONFIRMAR ASISTENCIA",
      successTitle: "⚓ ¡A BORDO, GRUMETE! ⚓",
      successExtra: "🏴‍☠️💰",
      punctual: "¡Llega puntual, el barco zarpa sin avisar!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  sirenas: {
    id: "sirenas",
    name: "Sirenas",
    emoji: "🧜‍♀️",
    category: "cumple_infantil",
    dark: false,
    font: "'Comfortaa', cursive",
    fontScale: 0.95,
    colors: { bg: "#ECFEFF", surface: "#FFFFFF", primary: "#0891B2", text: "#164E63", accent: "#F472B6", soft: "#A5F3FC" },
    image: "https://images.unsplash.com/photo-1533431557381-51a6546cf7ce?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🧜‍♀️", "🐚", "🫧", "🐠", "🌊", "⭐"],
    copy: {
      badge: (inv) => `Reino submarino de ${inv.child_name}`,
      title: (inv) => `¡La sirena ${inv.child_name} cumple ${inv.age} años!`,
      subtitle: (inv) => `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "🫧 La aventura submarina empieza en",
      details: "🐚 Detalles del arrecife 🐚",
      arrive: "🌊 Cómo llegar al océano",
      rsvpTitle: "🧜‍♀️ Registro de sirenas y tritones",
      rsvpSubtitle: "Confirma tu asistencia para nadar en la fiesta",
      confirm: "🐚 CONFIRMAR ASISTENCIA",
      successTitle: "🌊 ¡YA ERES PARTE DEL ARRECIFE! 🌊",
      successExtra: "🧜‍♀️🐠",
      punctual: "¡Llega puntual, la marea no espera!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  safari: {
    id: "safari",
    name: "Safari",
    emoji: "🦁",
    category: "cumple_infantil",
    dark: false,
    font: "'Baloo 2', cursive",
    fontScale: 0.95,
    colors: { bg: "#FFF7ED", surface: "#FFFFFF", primary: "#B45309", text: "#422006", accent: "#16A34A", soft: "#FDE68A" },
    image: "https://images.unsplash.com/photo-1754424578467-7c219061e45e?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🦁", "🐘", "🦒", "🌿", "🐾", "🌅"],
    copy: {
      badge: (inv) => `Safari de ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} cumple ${inv.age} años en la sabana!`,
      subtitle: (inv) => `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "🐾 La expedición safari sale en",
      details: "🌍 Datos de la expedición 🌍",
      arrive: "🗺️ Cómo llegar al safari",
      rsvpTitle: "🦁 Registro de exploradores",
      rsvpSubtitle: "Confirma tu asistencia para la aventura en la sabana",
      confirm: "🐘 CONFIRMAR ASISTENCIA",
      successTitle: "🦒 ¡EXPLORADOR LISTO PARA EL SAFARI! 🦒",
      successExtra: "🦁🌿",
      punctual: "¡Llega puntual, la manada no espera!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  granja: {
    id: "granja",
    name: "Granja",
    emoji: "🐮",
    category: "cumple_infantil",
    dark: false,
    font: "'Chewy', cursive",
    fontScale: 0.95,
    colors: { bg: "#FFFBEB", surface: "#FFFFFF", primary: "#CA8A04", text: "#713F12", accent: "#DC2626", soft: "#FEF08A" },
    image: "https://images.unsplash.com/photo-1768392927049-f0d92490fb5f?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🐮", "🐑", "🐔", "🐷", "🌾", "🚜"],
    copy: {
      badge: (inv) => `Granja de ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} cumple ${inv.age} añitos en la granja!`,
      subtitle: (inv) => `CUMPLE ${inv.age} AÑITOS 🎂`,
      countdown: "🚜 El paseo por la granja empieza en",
      details: "🌾 Detalles del corral 🌾",
      arrive: "🗺️ Cómo llegar a la granja",
      rsvpTitle: "🐮 Registro de granjeritos",
      rsvpSubtitle: "Confirma tu asistencia para dar de comer a los animalitos",
      confirm: "🐔 CONFIRMAR ASISTENCIA",
      successTitle: "🐷 ¡YA ERES PARTE DE LA GRANJA! 🐷",
      successExtra: "🐮🌾",
      punctual: "¡Llega puntual, el gallo ya cantó!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  fiesta_adultos: {
    id: "fiesta_adultos",
    name: "Fiesta Elegante",
    emoji: "🥂",
    category: "cumple_adulto",
    dark: true,
    font: "'Poiret One', cursive",
    fontScale: 1.15,
    colors: { bg: "#0D0D0D", surface: "#1A1A1A", primary: "#D4AF37", text: "#F5F5F5", accent: "#E11D48", soft: "#C9A94F" },
    image: "https://images.unsplash.com/photo-1647905555465-0f9004fbdaed?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["🥂", "🎉", "✨", "🎷", "🍾", "🌟"],
    copy: {
      badge: (inv) => `Fiesta de ${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} cumple ${inv.age}!`,
      subtitle: () => `UNA NOCHE PARA CELEBRAR 🥂`,
      countdown: "🕰️ La fiesta comienza en",
      details: "🍾 Detalles del evento 🍾",
      arrive: "🗺️ Cómo llegar",
      rsvpTitle: "🥂 Confirma tu asistencia",
      rsvpSubtitle: "Reserva tu lugar para brindar juntos",
      confirm: "🎉 CONFIRMAR ASISTENCIA",
      successTitle: "🥂 ¡NOS VEMOS EN LA FIESTA! 🥂",
      successExtra: "🎉✨",
      punctual: "La elegancia también es puntualidad",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
  boda: {
    id: "boda",
    name: "Boda Elegante",
    emoji: "💍",
    category: "boda",
    dark: false,
    font: "'Great Vibes', cursive",
    fontScale: 1.4,
    colors: { bg: "#FFFBF5", surface: "#FFFFFF", primary: "#A88763", text: "#3D2C1E", accent: "#D4AF37", soft: "#F1E4D0" },
    image: "https://images.unsplash.com/photo-1494955870715-979ca4f13bf0?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["💍", "👰", "🤵", "🥂", "🌹", "✨"],
    copy: {
      badge: (inv) => `${inv.child_name}`,
      title: (inv) => `¡${inv.child_name} nos casamos! 💍`,
      subtitle: (inv) => inv.event_subtitle || "Acompáñanos a celebrar nuestro amor",
      countdown: "💕 Nuestra boda es en",
      details: "🥂 Detalles de la celebración 🥂",
      arrive: "🗺️ Cómo llegar",
      rsvpTitle: "💍 Confirma tu asistencia",
      rsvpSubtitle: "Nos encantaría contar contigo en este día tan especial",
      confirm: "🌹 CONFIRMAR ASISTENCIA",
      successTitle: "💍 ¡GRACIAS POR CONFIRMAR! 💍",
      successExtra: "🥂✨",
      punctual: "Te esperamos puntuales para comenzar la celebración",
      msgLabel: () => `Mensaje para los novios (opcional)`,
    },
  },
  mundial: {
    id: "mundial",
    name: "Ver el Partido",
    emoji: "⚽",
    category: "partido",
    dark: true,
    font: "'Anton', sans-serif",
    fontScale: 0.95,
    colors: { bg: "#0B1F0F", surface: "#132B18", primary: "#22C55E", text: "#FFFFFF", accent: "#FBBF24", soft: "#86EFAC" },
    image: "https://images.unsplash.com/photo-1549333580-4cb2c5c8e421?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
    decorations: ["⚽", "🏆", "📣", "🎊", "🥅", "👕"],
    copy: {
      badge: (inv) => `¡Partidazo con ${inv.child_name}!`,
      title: (inv) => `¡${inv.child_name} te invita a ver el partido! ⚽`,
      subtitle: (inv) => inv.event_subtitle || "¡No te lo pierdas! 🎉",
      countdown: "⏱️ El pitazo inicial es en",
      details: "📋 Detalles del partido 📋",
      arrive: "🗺️ Cómo llegar",
      rsvpTitle: "⚽ Confirma tu lugar en la tribuna",
      rsvpSubtitle: "Dinos si vienes a alentar con nosotros",
      confirm: "🎉 CONFIRMAR ASISTENCIA",
      successTitle: "🏆 ¡GOOOL! YA ESTÁS EN LA LISTA 🏆",
      successExtra: "⚽🎉",
      punctual: "¡Llega antes del pitazo inicial!",
      msgLabel: (inv) => `Mensaje para ${inv.child_name} (opcional)`,
    },
  },
};

export const THEME_LIST = Object.values(THEMES);

export function formatDateEs(dateStr) {
  if (!dateStr) return "";
  const [y, m, d] = dateStr.split("-").map(Number);
  const date = new Date(y, m - 1, d);
  const s = date.toLocaleDateString("es-CO", { weekday: "long", day: "numeric", month: "long", year: "numeric" });
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export function formatTimeEs(timeStr) {
  if (!timeStr) return "";
  const [h, min] = timeStr.split(":").map(Number);
  const period = h < 12 ? "de la mañana" : h < 19 ? "de la tarde" : "de la noche";
  const h12 = h % 12 === 0 ? 12 : h % 12;
  return `${h12}:${String(min).padStart(2, "0")} ${period}`;
}

export function calendarUrl(inv) {
  if (!inv.event_date || !inv.event_time) return "#";
  const start = `${inv.event_date.replace(/-/g, "")}T${inv.event_time.replace(":", "")}00`;
  const [h, m] = inv.event_time.split(":").map(Number);
  const endH = Math.min(h + 4, 23);
  const end = `${inv.event_date.replace(/-/g, "")}T${String(endH).padStart(2, "0")}${String(m).padStart(2, "0")}00`;
  const params = new URLSearchParams({
    action: "TEMPLATE",
    text: `${inv.child_name || "Evento"} 🎉`,
    dates: `${start}/${end}`,
    details: `${inv.child_full_name || inv.child_name || ""}`,
    location: `${inv.venue}${inv.address ? ", " + inv.address : ""}`,
  });
  return `https://www.google.com/calendar/render?${params.toString()}`;
}

export function whatsappUrl(inv) {
  if (!inv.whatsapp) return null;
  const num = inv.whatsapp.replace(/\D/g, "");
  const text = encodeURIComponent(
    `¡Hola! Confirmo mi asistencia al evento de ${inv.child_name} 🎉 el ${formatDateEs(inv.event_date)}. Somos: `
  );
  return `https://wa.me/${num}?text=${text}`;
}
